/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import util.ConectaBD;
import vo.ProdutoVO;


/**
 *
 * @author Vinicius Meng
 */
public class DetalheProdutoFunc extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = -91472078671507360L;
	@SuppressWarnings("unused")
	private String s;
    private JFrame jF;
    private ProdutoVO pVo;
            
    public DetalheProdutoFunc(ProdutoVO pVo, JFrame jf) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jF = jf;
        this.pVo = pVo;
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível definir o look and feel do Windows!\nClassNotFoundException", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível definir o look and feel do Windows!\nInstantiationException", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível definir o look and feel do Windows!\nIllegalAccessException", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível definir o look and feel do Windows!\nUnsupportedLookAndFeelException", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        //this.s ="/imagens/" + "cliente" + ".png";
        //this.labelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource(s)));
        this.abreImagem();
        this.labelNome.setText(this.pVo.getNomeProduto());
        this.labelValor.setText(("Valor: R$ " + this.pVo.getValorUnitario() + "0").replace(".", ","));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImagem = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        labelQuantidade = new javax.swing.JLabel();
        textQuantidade = new javax.swing.JTextField();
        butComprar = new javax.swing.JButton();
        butCancelar = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalhes do Produto");

        labelValor.setText("Valor:");

        labelQuantidade.setText("Quantidade: ");

        textQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textQuantidadeKeyTyped(evt);
            }
        });

        butComprar.setText("Comprar");
        butComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butComprarActionPerformed(evt);
            }
        });

        butCancelar.setText("Cancelar");
        butCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarActionPerformed(evt);
            }
        });

        labelNome.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butComprar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butCancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textQuantidade))
                    .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textQuantidade)
                            .addComponent(labelQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butComprar)
                            .addComponent(butCancelar)))
                    .addComponent(labelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abreImagem(){
        Connection connection;
        try {
            connection = ConectaBD.getConnection();
            PreparedStatement statement = connection.prepareStatement("SELECT * FROM Imagem WHERE codigoImagem = ?");
            statement.setInt(1, pVo.getCodigoImagem());
            ResultSet resultSet = statement.executeQuery();
            resultSet.next();
            Blob blob = resultSet.getBlob("imagem");
            resultSet.close();
            statement.close();
            connection.close();
            ImageIcon imageIcon = new ImageIcon(blob.getBytes(1, (int)blob.length()));
            this.labelImagem.setIcon(imageIcon);
        } catch (SQLException ex) {
            Logger.getLogger(SalvaImagens.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível resgastar a imagem!\nSQLException", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SalvaImagens.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível resgastar a imagem!\nClassNotFoundException", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } 

    private void butCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_butCancelarActionPerformed

    private void textQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textQuantidadeKeyTyped
       String caracteres = "0987654321";
       if(!caracteres.contains(evt.getKeyChar() + "")){
              evt.consume();
       }
    }//GEN-LAST:event_textQuantidadeKeyTyped

    private void butComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butComprarActionPerformed
       int quantidade = Integer.parseInt(this.textQuantidade.getText());
       JanelaFuncionario janelFunc = (JanelaFuncionario) this.jF;
       janelFunc.atualizaQntComprada(quantidade);
       janelFunc.atualizaValorTotal(this.pVo.getValorUnitario(), quantidade);
       janelFunc.atualizaCarrinho("" + janelFunc.getQntComprada(), "" + ("R$ " + String.valueOf((janelFunc.getValorTotal()) + "0").replace(".", ",")));
       janelFunc.arrayQntCodProd(this.pVo.getCodigoProduto(), quantidade);
       this.dispose();
    }//GEN-LAST:event_butComprarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCancelar;
    private javax.swing.JButton butComprar;
    private javax.swing.JLabel labelImagem;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelValor;
    private javax.swing.JTextField textQuantidade;
    // End of variables declaration//GEN-END:variables
}
