/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.CompraDAO;
import dao.ProdutoDAO;
import excecoes.NSelecionouClienteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import vo.FuncionarioVO;
import vo.ProdutoVO;

/**
 *
 * @author 05200004
 */
public class JanelaFuncionario extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 7170489549874772760L;
	private ArrayList <ProdutoVO> produtos;
    private ArrayList <Integer> codProd;
    private ArrayList <Integer> qntProd;
    private CompraDAO cDao;
    private ProdutoDAO pDao;
    private DefaultTableModel dm;
    private float valorTotal;
    private int qntComprada;
    private int codComp;
    private int codCliente;
    private int codFunc;
    private TableRowSorter <DefaultTableModel> trs;
    
    /**
     * Creates new form JanelaFuncionario
     */
    public JanelaFuncionario(FuncionarioVO fVo) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.codFunc = fVo.getCodigoFuncionario();
        this.codCliente = -1;
        this.qntComprada = 0;
        this.valorTotal = 0;
        this.codProd = new ArrayList<Integer>();
        this.qntProd = new ArrayList<Integer>();
        this.cDao = new CompraDAO();
        this.pDao = new ProdutoDAO();
        this.labCodFunc.setText("Código do Funcionário: " + this.codFunc);
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível definir o look and feel do Windows!\nClassNotFoundException", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível definir o look and feel do Windows!\nInstantiationException", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível definir o look and feel do Windows!\nIllegalAccessException", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível definir o look and feel do Windows!\nUnsupportedLookAndFeelException", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        try {
            this.produtos = this.pDao.buscarProdutoAll();
        } catch (SQLException ex) {
            Logger.getLogger(JanelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível mostrar os produtos!\nSQLException", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível mostrar os produtos!\nClassNotFoundException", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        Object [] tituloColunas = {"Código do produto", "Nome do produto", "Valor unitário"};
        this.dm = new DefaultTableModel(){
            /**
			 * 
			 */
			private static final long serialVersionUID = 5761731470548576253L;

			@Override
            public boolean isCellEditable(int rowIndex, int mColIndex) {  
                return false;  
            }
        };
        this.dm.setDataVector(this.fazTabelProduto(), tituloColunas);
        this.tabelaProd.setModel(dm);
        this.trs = new TableRowSorter<DefaultTableModel>(this.dm);
        this.tabelaProd.setRowSorter(trs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCarrinho = new javax.swing.JPanel();
        labItensAd = new javax.swing.JLabel();
        labValTot = new javax.swing.JLabel();
        labItensVar = new javax.swing.JLabel();
        labValorVar = new javax.swing.JLabel();
        butComprar = new javax.swing.JButton();
        butLimpar = new javax.swing.JButton();
        labCli = new javax.swing.JLabel();
        butSelecionarCl = new javax.swing.JButton();
        butHistorico = new javax.swing.JButton();
        butDetalhesProd = new javax.swing.JButton();
        butSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProd = new javax.swing.JTable();
        nomeCliente = new javax.swing.JLabel();
        labExc = new javax.swing.JLabel();
        labCodCli = new javax.swing.JLabel();
        labCodFunc = new javax.swing.JLabel();
        textFiltrar = new javax.swing.JTextField();
        labFiltrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Funcionário");

        PainelCarrinho.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labItensAd.setText("Itens Adquiridos:");

        labValTot.setText("Valor Total:");

        butComprar.setText("Comprar");
        butComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butComprarActionPerformed(evt);
            }
        });

        butLimpar.setText("Limpar");
        butLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelCarrinhoLayout = new javax.swing.GroupLayout(PainelCarrinho);
        PainelCarrinho.setLayout(PainelCarrinhoLayout);
        PainelCarrinhoLayout.setHorizontalGroup(
            PainelCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCarrinhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCarrinhoLayout.createSequentialGroup()
                        .addComponent(labValTot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labValorVar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PainelCarrinhoLayout.createSequentialGroup()
                        .addComponent(butComprar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butLimpar)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(PainelCarrinhoLayout.createSequentialGroup()
                        .addComponent(labItensAd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labItensVar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PainelCarrinhoLayout.setVerticalGroup(
            PainelCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCarrinhoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labItensAd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labItensVar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labValTot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labValorVar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PainelCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butComprar)
                    .addComponent(butLimpar))
                .addContainerGap())
        );

        labCli.setText("Você está comprando para o cliente");

        butSelecionarCl.setText("Selecionar Cliente");
        butSelecionarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSelecionarClActionPerformed(evt);
            }
        });

        butHistorico.setText("Ver Histórico de Compras do Cliente");
        butHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butHistoricoActionPerformed(evt);
            }
        });

        butDetalhesProd.setText("Detalhes do Produto");
        butDetalhesProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDetalhesProdActionPerformed(evt);
            }
        });

        butSair.setText("Sair");
        butSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSairActionPerformed(evt);
            }
        });

        tabelaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaProd.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabelaProd);

        nomeCliente.setText("----------");

        labExc.setText("!");

        labCodCli.setText("Código do Cliente: ");

        labCodFunc.setText("Código do Funcionário: ");

        textFiltrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFiltrarKeyReleased(evt);
            }
        });

        labFiltrar.setText("Filtrar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butDetalhesProd)
                            .addComponent(butSair))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labCli)
                                .addGap(2, 2, 2)
                                .addComponent(nomeCliente)
                                .addGap(4, 4, 4)
                                .addComponent(labExc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(butSelecionarCl))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labCodCli)
                                    .addComponent(labCodFunc))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butHistorico)
                                .addGap(18, 18, 18)
                                .addComponent(labFiltrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFiltrar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PainelCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labCli)
                            .addComponent(butSelecionarCl)
                            .addComponent(nomeCliente)
                            .addComponent(labExc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labCodCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labCodFunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butHistorico)
                            .addComponent(textFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labFiltrar)))
                    .addComponent(PainelCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butDetalhesProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butSair))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butSelecionarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSelecionarClActionPerformed
        SelecionarCliente s = new SelecionarCliente(this);
        s.setVisible(true);
    }//GEN-LAST:event_butSelecionarClActionPerformed

    private void butSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSairActionPerformed
        JanelaPrincipal jp = new JanelaPrincipal();
        jp.setVisible(true);
        dispose();
    }//GEN-LAST:event_butSairActionPerformed

    private void butHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butHistoricoActionPerformed
        if(this.codCliente == -1){
            try {
                throw new NSelecionouClienteException();
            } catch (NSelecionouClienteException ex) {
                Logger.getLogger(JanelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            Historico h = new Historico(this.codCliente);
            h.setVisible(true);
        }
    }//GEN-LAST:event_butHistoricoActionPerformed

    private void butLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLimparActionPerformed
       this.labItensVar.setText("");
       this.labValorVar.setText("");
       this.valorTotal = 0;
       this.qntComprada = 0;
       this.codProd.clear();
       this.qntProd.clear();
    }//GEN-LAST:event_butLimparActionPerformed

    private void butDetalhesProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDetalhesProdActionPerformed
        try{
            if(this.codCliente == -1){
                try{
                    throw new NSelecionouClienteException();
                } catch (NSelecionouClienteException ex){
                    Logger.getLogger(JanelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                int produtoSelecionado = (Integer)this.tabelaProd.getValueAt(this.tabelaProd.getSelectedRow(), 0);
                ProdutoVO pVoSelecionado = null;
                for (ProdutoVO produto : this.produtos) {
                    if (produtoSelecionado == produto.getCodigoProduto()) {
                        pVoSelecionado = produto;
                    }
                }
                DetalheProdutoFunc dp = new DetalheProdutoFunc(pVoSelecionado, JanelaFuncionario.this);
                dp.setVisible(true);
            }
        } catch(java.lang.IndexOutOfBoundsException ex){
            Logger.getLogger(JanelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Você deve selecionar um produto primeiro!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_butDetalhesProdActionPerformed

    private void butComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butComprarActionPerformed
        ConfirmaCompra cc = new ConfirmaCompra(this.codCliente, this.codComp, this.produtos, this.codProd, this.qntProd);
        cc.setVisible(true);
    }//GEN-LAST:event_butComprarActionPerformed

    private void textFiltrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFiltrarKeyReleased
        RowFilter<DefaultTableModel, Object> regexFilter = RowFilter.regexFilter(this.textFiltrar.getText() + "");
        this.trs.setRowFilter(regexFilter);
    }//GEN-LAST:event_textFiltrarKeyReleased

    public void setNomeCliente(String nome, int cod){
        this.nomeCliente.setText(nome);
        this.codCliente = cod;
        this.labCodCli.setText("Código do Cliente: " + cod);
        try {
            this.codComp = this.cDao.codigoClienteMax() + 1;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JanelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possivel criar um código para a compra!\nClassNotFoundException", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(JanelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possivel criar um código para a compra!\nSQLException", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private Object[][] fazTabelProduto(){
        Object[][] dados = new Object[this.produtos.size()][3];
        for (int i = 0; i < this.produtos.size(); i++) {
            dados[i][0] = this.produtos.get(i).getCodigoProduto();
            dados[i][1] = this.produtos.get(i).getNomeProduto();
            String valor = ("R$ " + this.produtos.get(i).getValorUnitario() + "0").replace(".", ",");
            dados[i][2] = valor;
        }
        return dados;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelCarrinho;
    private javax.swing.JButton butComprar;
    private javax.swing.JButton butDetalhesProd;
    private javax.swing.JButton butHistorico;
    private javax.swing.JButton butLimpar;
    private javax.swing.JButton butSair;
    private javax.swing.JButton butSelecionarCl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labCli;
    private javax.swing.JLabel labCodCli;
    private javax.swing.JLabel labCodFunc;
    private javax.swing.JLabel labExc;
    private javax.swing.JLabel labFiltrar;
    private javax.swing.JLabel labItensAd;
    private javax.swing.JLabel labItensVar;
    private javax.swing.JLabel labValTot;
    private javax.swing.JLabel labValorVar;
    private javax.swing.JLabel nomeCliente;
    private javax.swing.JTable tabelaProd;
    private javax.swing.JTextField textFiltrar;
    // End of variables declaration//GEN-END:variables
    
    public void atualizaCarrinho (String qnt, String valor){
        this.labItensVar.setText(qnt);
        this.labValorVar.setText(valor);
    }
    
    public void atualizaValorTotal(float valorTotal, int qntProd) {
        this.valorTotal += valorTotal * qntProd;
    }

    public void atualizaQntComprada(int qntComprada) {
        this.qntComprada += qntComprada;
    }
    
    public void arrayQntCodProd(int codProd, int qntProd){
        this.codProd.add(codProd);
        this.qntProd.add(qntProd);
    }

    public float getValorTotal() {
        return valorTotal;
    }

    public int getQntComprada() {
        return qntComprada;
    }
}
