/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.ClienteDAO;
import dao.FuncionarioDAO;
import excecoes.IsNotGerenteException;
import excecoes.SenhaIncorretaException;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import util.Hash;
import vo.ClienteVO;
import vo.FuncionarioVO;

/**
 *
 * @author Vinicius Meng
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        JOptionPane.showMessageDialog(null, "LoginCliente: 15 - oioioi\nLoginFuncionário: 4 - oioioi\nLoginGerente: 3 - matrix", "Logins", JOptionPane.INFORMATION_MESSAGE);
        initComponents();
        this.setLocationRelativeTo(null);
        this.painelCliente.setVisible(false);
        this.painelFuncionario.setVisible(false);
        this.painelGerente.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        painelLayers = new javax.swing.JLayeredPane();
        painelPrincipal = new javax.swing.JPanel();
        butCliente = new javax.swing.JButton();
        butFuncionario = new javax.swing.JButton();
        butGerente = new javax.swing.JButton();
        labelVc = new javax.swing.JLabel();
        imagemCliente = new javax.swing.JLabel();
        imagemFunc = new javax.swing.JLabel();
        imagemGerente = new javax.swing.JLabel();
        labelBemVindo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        painelCliente = new javax.swing.JPanel();
        labelJaCliente = new javax.swing.JLabel();
        labelCodigoLoginCli = new javax.swing.JLabel();
        labelSenhaLoginCli = new javax.swing.JLabel();
        textCodigoLoginCli = new javax.swing.JTextField();
        butLoginCli = new javax.swing.JButton();
        labelNCliente = new javax.swing.JLabel();
        butCadastrarCli = new javax.swing.JButton();
        butVoltarCli = new javax.swing.JButton();
        textSenhaCli = new javax.swing.JPasswordField();
        painelFuncionario = new javax.swing.JPanel();
        labelFunc = new javax.swing.JLabel();
        labelCodigoLoginFunc = new javax.swing.JLabel();
        labelSenhaLoginFunc = new javax.swing.JLabel();
        textCodigoLoginFunc = new javax.swing.JTextField();
        butLoginFunc = new javax.swing.JButton();
        butVoltarFunc = new javax.swing.JButton();
        textSenhaFunc = new javax.swing.JPasswordField();
        painelGerente = new javax.swing.JPanel();
        labelGerente = new javax.swing.JLabel();
        labelCodigoLoginGerente = new javax.swing.JLabel();
        labelSenhaLoginGerente = new javax.swing.JLabel();
        textCodigoLoginGerente = new javax.swing.JTextField();
        butLoginGerente = new javax.swing.JButton();
        butVoltarGerente = new javax.swing.JButton();
        textSenhaGer = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hipermercado Bregaboys v0.1");

        butCliente.setText("Cliente");
        butCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butClienteActionPerformed(evt);
            }
        });

        butFuncionario.setText("Funcionário");
        butFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFuncionarioActionPerformed(evt);
            }
        });

        butGerente.setText("Gerente");
        butGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGerenteActionPerformed(evt);
            }
        });

        labelVc.setText("Você é:");

        imagemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N

        imagemFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionario.png"))); // NOI18N

        imagemGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gerente.png"))); // NOI18N

        labelBemVindo.setText("Bem-vindo ao programa do hipermercado Bregaboys! (Em breve Ultramercado)");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(imagemCliente)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(butCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagemFunc)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(butFuncionario)))
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(imagemGerente))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(butGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(229, 229, 229))
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(labelVc))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(labelBemVindo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelBemVindo)
                .addGap(36, 36, 36)
                .addComponent(labelVc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(imagemCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagemFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagemGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butCliente)
                    .addComponent(butFuncionario)
                    .addComponent(butGerente))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        labelJaCliente.setText("Já é um cliente? Faça o login:");

        labelCodigoLoginCli.setText("Código");

        labelSenhaLoginCli.setText("Senha");

        textCodigoLoginCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCodigoLoginCliKeyTyped(evt);
            }
        });

        butLoginCli.setText("Login");
        butLoginCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoginCliActionPerformed(evt);
            }
        });

        labelNCliente.setText("Não é? Cadastre-se:");

        butCadastrarCli.setText("Cadastrar");
        butCadastrarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCadastrarCliActionPerformed(evt);
            }
        });

        butVoltarCli.setText("Voltar");
        butVoltarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVoltarCliActionPerformed(evt);
            }
        });

        textSenhaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSenhaCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelClienteLayout = new javax.swing.GroupLayout(painelCliente);
        painelCliente.setLayout(painelClienteLayout);
        painelClienteLayout.setHorizontalGroup(
            painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelClienteLayout.createSequentialGroup()
                .addGap(29, 178, Short.MAX_VALUE)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNCliente)
                    .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelClienteLayout.createSequentialGroup()
                            .addComponent(labelJaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelClienteLayout.createSequentialGroup()
                            .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(painelClienteLayout.createSequentialGroup()
                                    .addComponent(labelCodigoLoginCli)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(textCodigoLoginCli, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(butLoginCli)
                                .addGroup(painelClienteLayout.createSequentialGroup()
                                    .addComponent(labelSenhaLoginCli)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(textSenhaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(butCadastrarCli))
                            .addGap(204, 204, 204)))))
            .addGroup(painelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butVoltarCli)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelClienteLayout.setVerticalGroup(
            painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelClienteLayout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(labelJaCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCodigoLoginCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCodigoLoginCli, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenhaLoginCli, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSenhaCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butLoginCli)
                .addGap(11, 11, 11)
                .addComponent(labelNCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butCadastrarCli)
                .addGap(133, 133, 133)
                .addComponent(butVoltarCli)
                .addContainerGap())
        );

        labelFunc.setText("Funcionário, logue-se:");

        labelCodigoLoginFunc.setText("Código");

        labelSenhaLoginFunc.setText("Senha");

        textCodigoLoginFunc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCodigoLoginFuncKeyTyped(evt);
            }
        });

        butLoginFunc.setText("Login");
        butLoginFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoginFuncActionPerformed(evt);
            }
        });

        butVoltarFunc.setText("Voltar");
        butVoltarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVoltarFuncActionPerformed(evt);
            }
        });

        textSenhaFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSenhaFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelFuncionarioLayout = new javax.swing.GroupLayout(painelFuncionario);
        painelFuncionario.setLayout(painelFuncionarioLayout);
        painelFuncionarioLayout.setHorizontalGroup(
            painelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFuncionarioLayout.createSequentialGroup()
                .addGroup(painelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFuncionarioLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(labelFunc))
                    .addGroup(painelFuncionarioLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addGroup(painelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(butLoginFunc)
                            .addGroup(painelFuncionarioLayout.createSequentialGroup()
                                .addGroup(painelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFuncionarioLayout.createSequentialGroup()
                                        .addComponent(labelCodigoLoginFunc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(painelFuncionarioLayout.createSequentialGroup()
                                        .addComponent(labelSenhaLoginFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)))
                                .addGroup(painelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textCodigoLoginFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(textSenhaFunc)))))
                    .addGroup(painelFuncionarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(butVoltarFunc)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        painelFuncionarioLayout.setVerticalGroup(
            painelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFuncionarioLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(labelFunc)
                .addGap(14, 14, 14)
                .addGroup(painelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textCodigoLoginFunc)
                    .addComponent(labelCodigoLoginFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenhaLoginFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSenhaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butLoginFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(butVoltarFunc)
                .addContainerGap())
        );

        labelGerente.setText("Gerente, logue-se:");

        labelCodigoLoginGerente.setText("Código");

        labelSenhaLoginGerente.setText("Senha");

        textCodigoLoginGerente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCodigoLoginGerenteKeyTyped(evt);
            }
        });

        butLoginGerente.setText("Login");
        butLoginGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoginGerenteActionPerformed(evt);
            }
        });

        butVoltarGerente.setText("Voltar");
        butVoltarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVoltarGerenteActionPerformed(evt);
            }
        });

        textSenhaGer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSenhaGerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelGerenteLayout = new javax.swing.GroupLayout(painelGerente);
        painelGerente.setLayout(painelGerenteLayout);
        painelGerenteLayout.setHorizontalGroup(
            painelGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGerenteLayout.createSequentialGroup()
                .addGroup(painelGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelGerenteLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(labelGerente))
                    .addGroup(painelGerenteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(butVoltarGerente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGerenteLayout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addGroup(painelGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGerenteLayout.createSequentialGroup()
                        .addGroup(painelGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCodigoLoginGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSenhaLoginGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textCodigoLoginGerente, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(textSenhaGer))
                        .addGap(204, 204, 204))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelGerenteLayout.createSequentialGroup()
                        .addComponent(butLoginGerente)
                        .addGap(201, 201, 201))))
        );
        painelGerenteLayout.setVerticalGroup(
            painelGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelGerenteLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(labelGerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigoLoginGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCodigoLoginGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(painelGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenhaLoginGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSenhaGer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butLoginGerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(butVoltarGerente)
                .addContainerGap())
        );

        javax.swing.GroupLayout painelLayersLayout = new javax.swing.GroupLayout(painelLayers);
        painelLayers.setLayout(painelLayersLayout);
        painelLayersLayout.setHorizontalGroup(
            painelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelLayersLayout.createSequentialGroup()
                    .addComponent(painelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(painelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelLayersLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        painelLayersLayout.setVerticalGroup(
            painelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelLayersLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        painelLayers.setLayer(painelPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelLayers.setLayer(painelCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelLayers.setLayer(painelFuncionario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelLayers.setLayer(painelGerente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLayers)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLayers)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butClienteActionPerformed
        this.painelPrincipal.setVisible(false);
        this.painelCliente.setVisible(true);
        this.painelLayers.moveToFront(this.painelCliente);
        this.textCodigoLoginCli.requestFocus();
    }//GEN-LAST:event_butClienteActionPerformed

    private void butFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butFuncionarioActionPerformed
        this.painelPrincipal.setVisible(false);
        this.painelFuncionario.setVisible(true);
        this.painelLayers.moveToFront(this.painelFuncionario);
        this.textCodigoLoginFunc.requestFocus();
    }//GEN-LAST:event_butFuncionarioActionPerformed

    private void butGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGerenteActionPerformed
        this.painelPrincipal.setVisible(false);
        this.painelGerente.setVisible(true);
        this.painelLayers.moveToFront(this.painelGerente);
        this.textCodigoLoginGerente.requestFocus(); 
    }//GEN-LAST:event_butGerenteActionPerformed

    private void butCadastrarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCadastrarCliActionPerformed
        CadastraCliente cc = new CadastraCliente();
        cc.setVisible(true);
    }//GEN-LAST:event_butCadastrarCliActionPerformed

    private void butVoltarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVoltarCliActionPerformed
        this.painelCliente.setVisible(false);
        this.painelPrincipal.setVisible(true);
        this.painelLayers.moveToFront(this.painelPrincipal);
    }//GEN-LAST:event_butVoltarCliActionPerformed

    private void butVoltarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVoltarFuncActionPerformed
        this.painelFuncionario.setVisible(false);
        this.painelPrincipal.setVisible(true);
        this.painelLayers.moveToFront(this.painelPrincipal);
    }//GEN-LAST:event_butVoltarFuncActionPerformed

    private void butVoltarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVoltarGerenteActionPerformed
        this.painelGerente.setVisible(false);
        this.painelPrincipal.setVisible(true);
        this.painelLayers.moveToFront(this.painelPrincipal);
    }//GEN-LAST:event_butVoltarGerenteActionPerformed
  
    private void butLoginCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoginCliActionPerformed
        ClienteDAO e = new ClienteDAO();
        try {
            ClienteVO cVo = e.buscarCliente(Integer.parseInt(this.textCodigoLoginCli.getText()));
            String senhaDigitada = Hash.hashingSenha(String.valueOf(this.textSenhaCli.getPassword()));
            if(!senhaDigitada.equals(cVo.getSenhaCliente())){
                throw new SenhaIncorretaException();
            }
            else{
                JanelaCliente jc = new JanelaCliente(cVo);
                jc.setVisible(true);
                this.dispose();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o login!\nClassNotFoundException", "Erro", JOptionPane.ERROR_MESSAGE);
            this.textSenhaCli.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o login!\nSQLException", "Erro", JOptionPane.ERROR_MESSAGE);
            this.textSenhaCli.setText("");
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o login!\nNoSuchAlgorithmException", "Erro", JOptionPane.ERROR_MESSAGE);
            this.textSenhaCli.setText("");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o login!\nUnsupportedEncodingException", "Erro", JOptionPane.ERROR_MESSAGE);
            this.textSenhaCli.setText("");
        } catch (SenhaIncorretaException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            this.textSenhaCli.setText("");
        }
        catch(NumberFormatException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "O código não pode ficar em branco!", "Erro", JOptionPane.ERROR_MESSAGE);
            this.textSenhaFunc.setText("");
        }
    }//GEN-LAST:event_butLoginCliActionPerformed

    private void textSenhaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSenhaCliActionPerformed
        this.butLoginCliActionPerformed(evt);
    }//GEN-LAST:event_textSenhaCliActionPerformed

    private void butLoginFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoginFuncActionPerformed
        FuncionarioDAO e = new FuncionarioDAO();
        try {
            FuncionarioVO fVo = e.buscarFuncionario(Integer.parseInt(this.textCodigoLoginFunc.getText()));
            String senhaDigitada = Hash.hashingSenha(String.valueOf(this.textSenhaFunc.getPassword()));
            if(!senhaDigitada.equals(fVo.getSenhaFuncionario())){
                throw new SenhaIncorretaException();
            }
            else{
                JanelaFuncionario jf = new JanelaFuncionario(fVo);
                jf.setVisible(true);
                this.dispose();
            }
         
        } catch (SenhaIncorretaException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            this.textSenhaFunc.setText("");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o login!\nClassNotFoundException", "Erro", JOptionPane.ERROR_MESSAGE);
            this.textSenhaFunc.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o login!\nSQLException", "Erro", JOptionPane.ERROR_MESSAGE);
            this.textSenhaFunc.setText("");
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o login!\nNoSuchAlgorithmException", "Erro", JOptionPane.ERROR_MESSAGE);
            this.textSenhaFunc.setText("");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o login!\nUnsupportedEncodingException", "Erro", JOptionPane.ERROR_MESSAGE);
            this.textSenhaFunc.setText("");
        } catch(NumberFormatException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "O código não pode ficar em branco!", "Erro", JOptionPane.ERROR_MESSAGE);
            this.textSenhaFunc.setText("");
        }
    }//GEN-LAST:event_butLoginFuncActionPerformed

    private void textSenhaFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSenhaFuncActionPerformed
        this.butLoginFuncActionPerformed(evt);
    }//GEN-LAST:event_textSenhaFuncActionPerformed

    private void textCodigoLoginCliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCodigoLoginCliKeyTyped
       String caracteres = "0987654321";
       if(!caracteres.contains(evt.getKeyChar() + "")){
              evt.consume();
       }
    }//GEN-LAST:event_textCodigoLoginCliKeyTyped

    private void textCodigoLoginFuncKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCodigoLoginFuncKeyTyped
       String caracteres = "0987654321";
       if(!caracteres.contains(evt.getKeyChar() + "")){
              evt.consume();
       }
    }//GEN-LAST:event_textCodigoLoginFuncKeyTyped

    private void textCodigoLoginGerenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCodigoLoginGerenteKeyTyped
       String caracteres = "0987654321";
       if(!caracteres.contains(evt.getKeyChar() + "")){
              evt.consume();
       }
    }//GEN-LAST:event_textCodigoLoginGerenteKeyTyped

    private void butLoginGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoginGerenteActionPerformed
        FuncionarioDAO e = new FuncionarioDAO();
        try {
            FuncionarioVO fVo = e.buscarFuncionario(Integer.parseInt(this.textCodigoLoginGerente.getText()));
            String senhaDigitada = Hash.hashingSenha(String.valueOf(this.textSenhaGer.getPassword()));
            if(!senhaDigitada.equals(fVo.getSenhaFuncionario())){
                throw new SenhaIncorretaException();
            }
            else if(fVo.getCodigoFuncionario() != fVo.getCodigoGerente()){
                throw new IsNotGerenteException();
            }
            else{
                JanelaGerente gc = new JanelaGerente(fVo);
                gc.setVisible(true);
                this.dispose();
            }
         
        } catch (SenhaIncorretaException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            this.textSenhaGer.setText("");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o login!\nClassNotFoundException", "Erro", JOptionPane.ERROR_MESSAGE);
            this.textSenhaGer.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o login!\nSQLException", "Erro", JOptionPane.ERROR_MESSAGE);
            this.textSenhaGer.setText("");
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o login!\nNoSuchAlgorithmException", "Erro", JOptionPane.ERROR_MESSAGE);
            this.textSenhaGer.setText("");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível fazer o login!\nUnsupportedEncodingException", "Erro", JOptionPane.ERROR_MESSAGE);
            this.textSenhaGer.setText("");
        } catch(NumberFormatException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "O código não pode ficar em branco!", "Erro", JOptionPane.ERROR_MESSAGE);
            this.textSenhaGer.setText("");
        } catch (IsNotGerenteException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_butLoginGerenteActionPerformed

    private void textSenhaGerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSenhaGerActionPerformed
        this.butLoginGerenteActionPerformed(evt);
    }//GEN-LAST:event_textSenhaGerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível definir o look and feel do Windows!\nClassNotFoundException", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível definir o look and feel do Windows!\nInstantiationException", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível definir o look and feel do Windows!\nIllegalAccessException", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível definir o look and feel do Windows!\nUnsupportedLookAndFeelException", "Erro", JOptionPane.ERROR_MESSAGE);
        } 
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCadastrarCli;
    private javax.swing.JButton butCliente;
    private javax.swing.JButton butFuncionario;
    private javax.swing.JButton butGerente;
    private javax.swing.JButton butLoginCli;
    private javax.swing.JButton butLoginFunc;
    private javax.swing.JButton butLoginGerente;
    private javax.swing.JButton butVoltarCli;
    private javax.swing.JButton butVoltarFunc;
    private javax.swing.JButton butVoltarGerente;
    private javax.swing.JLabel imagemCliente;
    private javax.swing.JLabel imagemFunc;
    private javax.swing.JLabel imagemGerente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel labelBemVindo;
    private javax.swing.JLabel labelCodigoLoginCli;
    private javax.swing.JLabel labelCodigoLoginFunc;
    private javax.swing.JLabel labelCodigoLoginGerente;
    private javax.swing.JLabel labelFunc;
    private javax.swing.JLabel labelGerente;
    private javax.swing.JLabel labelJaCliente;
    private javax.swing.JLabel labelNCliente;
    private javax.swing.JLabel labelSenhaLoginCli;
    private javax.swing.JLabel labelSenhaLoginFunc;
    private javax.swing.JLabel labelSenhaLoginGerente;
    private javax.swing.JLabel labelVc;
    private javax.swing.JPanel painelCliente;
    private javax.swing.JPanel painelFuncionario;
    private javax.swing.JPanel painelGerente;
    private javax.swing.JLayeredPane painelLayers;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JTextField textCodigoLoginCli;
    private javax.swing.JTextField textCodigoLoginFunc;
    private javax.swing.JTextField textCodigoLoginGerente;
    private javax.swing.JPasswordField textSenhaCli;
    private javax.swing.JPasswordField textSenhaFunc;
    private javax.swing.JPasswordField textSenhaGer;
    // End of variables declaration//GEN-END:variables
}
